require 'rbconfig'

# Standardize on postgres
#   Check/assume logged-in user can create databases
#   Use min_warnings
#   config/database.yml.example and perform overwrite
#   Write to readme
#
gem "pg"

gem 'devise', '~> 3.2.4'
gem 'bootstrap-sass'
gem 'font-awesome-sass'

gem_group :development, :test do
  gem 'rspec-rails', '~> 2.14.2'
  gem 'pry'
  gem 'pry-rails'
  gem 'pry-byebug'
  gem 'pry-awesome_print'
  gem 'guard-rspec'
  gem 'guard-bundler'
  gem 'rb-fsevent'
end

gem_group :test do
  gem 'capybara'
  gem 'capybara-webkit'
  gem 'factory_girl_rails', '4.1.0'
  gem 'forgery'
  gem 'launchy'
  gem 'database_cleaner'
end

run 'rm .gitignore'
file '.gitignore', <<-GITIGNORE
# See http://help.github.com/ignore-files/ for more about ignoring files.
#
# If you find yourself ignoring temporary files generated by your text editor
# or operating system, you probably want to add a global ignore instead:
#   git config --global core.excludesfile ~/.gitignore_global

# Ignore bundler config
/.bundle

# Ignore the default SQLite database.
/db/*.sqlite3

# Ignore all logfiles and tempfiles.
/log/*.log*
/tmp

config/database.yml
vendor/bundle
GITIGNORE


environment <<-APP_GENERATORS
  config.generators do |g|
    g.orm :active_record
    g.test_framework :rspec, 
      :fixtures => true, 
      :view_specs => false, 
      :helper_specs => false, 
      :routing_specs => false, 
      :controller_specs => false, 
      :request_specs => true
    g.fixture_replacement :factory_girl, :dir => "spec/factories"
  end
  config.time_zone = 'Eastern Time (US & Canada)'
APP_GENERATORS

file "spec/support/capybara.rb", <<-CAPYBARA
require 'capybara/rails'
require 'capybara/rspec'

RSpec.configure do |config|
  #config.include Rails.application.routes.url_helpers

  Capybara.javascript_driver = :webkit
end
CAPYBARA

file "spec/support/factory_girl.rb", <<-FACTORY_GIRL
RSpec.configure do |config|
  config.include FactoryGirl::Syntax::Methods
end
FACTORY_GIRL

file "spec/support/db_cleaner.rb", <<-DB_CLEANER
require 'database_cleaner'
RSpec.configure do |config|

  config.before(:suite) do
    DatabaseCleaner.strategy = :transaction
    DatabaseCleaner.clean_with(:truncation)
  end

  config.before(:each) do
    DatabaseCleaner.start
  end

  config.after(:each) do
    DatabaseCleaner.clean
  end

end
DB_CLEANER

app_name = ARGV[0]

file "config/database.yml.example", <<-DATABASE
development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: #{app_name}_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: #{app_name}_test
  pool: 5
  username:
  password:
  min_messages: warning

production:
  adapter: postgresql
  encoding: unicode
  database: #{app_name}_production
  pool: 5
  username:
  password:
  min_messages: warning
DATABASE

run "bundle install"

generate "rspec:install"
run "mkdir spec/features"
run "bundle exec guard init"
run "rm config/database.yml; cp config/database.yml.example config/database.yml"
rake "db:create:all"

generate "devise:install"
generate "devise User"
generate "devise:views"

rake "db:migrate db:test:prepare"

# Handles two suggestions from Devise install process

environment "config.action_mailer.default_url_options = {host: 'localhost:#{port}'}", env: 'development'

generate "controller welcome index"

route "root to: 'welcome#index'"

# Use SCSS instead of CSS
run "rm app/assets/stylesheets/application.css; touch app/assets/stylesheets/application.scss"

# Installs twitter bootstrap
#
if yes?("Use Twitter bootstrap?")
  append_file 'app/assets/javascripts/application.js', '//= require bootstrap'
  append_file 'app/assets/stylesheets/application.scss', '@import "bootstrap";'
  append_file 'app/assets/stylesheets/application.scss', '@import "font-awesome";'
  run "curl https://raw.github.com/timcheadle/rails-templates/master/application.html.erb -o app/views/layouts/application.html.erb"
  run "curl https://raw.github.com/timcheadle/rails-templates/master/_header.html.erb -o app/views/layouts/_header.html.erb"
  run "curl https://raw.github.com/timcheadle/rails-templates/master/_footer.html.erb -o app/views/layouts/_footer.html.erb"
  run "curl https://raw.github.com/timcheadle/rails-templates/master/index.html.erb -o app/views/welcome/index.html.erb"
else
  puts "Please inspect your Gemfile to remove the gem"
  puts "Also modify app/views/layouts/application.html.erb file to remove Bootstrap-style layout"
end

git :init
git add: "."
git commit: %Q{ -m 'Initial commit' }
